/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the "Building Java & JVM projects" chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.3/userguide/building_java_projects.html
 */

plugins {
  application
  id("com.gradleup.shadow").version("8.3.0")
  jacoco
}

repositories {
  mavenCentral()
  maven {
    name = "m2-dv8tion"
    url = uri("https://m2.dv8tion.net/releases")
  }
  maven {
    url = uri("https://jitpack.io")
  }
}

dependencies {
  implementation(libs.guava)
  implementation(libs.jda)
  implementation(libs.logback.classic)
  implementation(libs.re2j)
  implementation(libs.bundles.jackson)

  implementation(
    fileTree(
      mapOf(
        "dir" to layout.projectDirectory.dir("../native").asFile,
        "include" to listOf("hajimeapi4j.jar")
      )
    )
  )

  implementation(libs.jakarta.annotation)

  compileOnly(libs.lombok)
  annotationProcessor(libs.lombok)

  testRuntimeOnly(libs.junit.platform.launcher)
  testImplementation(libs.junit.jupiter)
  testCompileOnly(libs.lombok)
  testAnnotationProcessor(libs.lombok)
}

application {
  mainClass.set("MochiMochiTalk.App")
}

tasks.withType<JavaCompile> {
  options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
  useJUnitPlatform()
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
  mergeServiceFiles()
}

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}
