/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the "Building Java & JVM projects" chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
  application
  id("com.github.johnrengelman.shadow") version "8.1.1"
  jacoco
}

repositories {
  mavenCentral()
  maven {
    name = "m2-dv8tion"
    url = uri("https://m2.dv8tion.net/releases")
  }
  maven {
    url = uri("https://jitpack.io")
  }
}

val jacksonVersion = "2.19.2"

dependencies {
  testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.13.4")
  testImplementation("org.junit.jupiter:junit-jupiter:5.13.4")

  implementation("com.google.guava:guava:33.5.0-jre")

  implementation("net.dv8tion:JDA:5.6.1")

  implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")
  annotationProcessor("jakarta.annotation:jakarta.annotation-api:3.0.0")

  implementation("ch.qos.logback:logback-classic:1.5.27")

  implementation("com.google.re2j:re2j:1.8")

  implementation("com.fasterxml.jackson.core:jackson-core:${jacksonVersion}")
  implementation("com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}")
  implementation("com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}")

  implementation(fileTree(mapOf("dir" to "..\\native", "include" to listOf("hajimeapi4j.jar"))))

  implementation("org.projectlombok:lombok:1.18.42")
  annotationProcessor("org.projectlombok:lombok:1.18.42")

  testImplementation("org.projectlombok:lombok:1.18.42")
  testAnnotationProcessor("org.projectlombok:lombok:1.18.42")
}

application {
  mainClass.set("MochiMochiTalk.App")
}

tasks.withType<JavaCompile> {
  options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
  useJUnitPlatform()
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
  mergeServiceFiles()
}

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}
