/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MochiMochiTalk;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void testApp() {
    assertTrue(true);
  }
}
