/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MochiMochiTalk;

import javax.security.auth.login.LoginException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import MochiMochiTalk.Listeners.ReadyListener;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

public class App {

    private static final String TOKEN = "OTI3NzkwMDQ2NzkzMzE4NDQw.YdPV0A.aXz6PxWBwvFoHA2vB00IfMiOZSc";
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static String prefix = "!!";

    public static void main(String[] args) {
        logger.info("Hello, world!");
        JDABuilder builder = JDABuilder.createDefault(TOKEN);
        logger.info("TOKEN was successfully set.");
        try {
            builder.disableCache(CacheFlag.MEMBER_OVERRIDES)
            .setBulkDeleteSplittingEnabled(false)
            .setActivity(Activity.competing("ドリームホープスプリング"))
            .setStatus(OnlineStatus.ONLINE)
            .addEventListeners(
                new ReadyListener()
            )
            .build();
            logger.info("JDA was successfully built.");
        } catch (LoginException e) {
            logger.error("Failed to login.", e);
        }
    }
}
